terraform {
  required_version = ">= 1.10.0, < 1.11.0"

  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "6.25.0"
    }

    archive = {
      source = "hashicorp/archive"
      version = "2.7.1"
    }
  }
}

provider "aws" {
  region = var.region
  profile = var.aws_profile
}

# --- 1. S3 Bucket Definition ---
resource "aws_s3_bucket" "demo" {
  bucket = "${var.name_prefix}-demo-s3-trigger-lambda-bucket"

  force_destroy = true
}


# --- 2. IAM Role for Lambda Execution ---
# Defines the trust relationship for the Lambda service
resource "aws_iam_role" "lambda_exec" {
  name = "${var.name_prefix}-demo-s3-trigger-lambda-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17",
    Statement = [{
      Action = "sts:AssumeRole",
      Effect = "Allow",
      Principal = {
        Service = "lambda.amazonaws.com"
      }
    }]
  })
}

# Policy for logging and S3 read access
resource "aws_iam_policy" "lambda_s3" {
  name        = "${var.name_prefix}-demo-s3-trigger-lambda-role"
  description = "Allows Lambda to log and read from the S3 bucket."

  policy = jsonencode({
    Version = "2012-10-17",
    Statement = [
      # Basic logging permissions
      {
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ],
        Effect   = "Allow",
        Resource = "arn:aws:logs:*:*:*"
      },
      # S3 Read-Only permissions for the specific bucket
      {
        Action = [
          "s3:GetObject"
        ],
        Effect   = "Allow",
        Resource = "${aws_s3_bucket.demo.arn}/*"
      },
      # Needed to list and describe buckets/objects
      {
        Action   = "s3:ListBucket",
        Effect   = "Allow",
        Resource = aws_s3_bucket.demo.arn
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "lambda" {
  role       = aws_iam_role.lambda_exec.name
  policy_arn = aws_iam_policy.lambda_s3.arn
}

# --- 3. Lambda Deployment Package (Zip the Python code) ---
data "archive_file" "lambda_zip" {
  type        = "zip"
  source_file = "../process.py"
  output_path = "process.zip"
}

# --- 4. Lambda Function Definition ---
resource "aws_lambda_function" "s3_processor" {
  # This uses the zip generated by the data block above
  filename         = data.archive_file.lambda_zip.output_path
  function_name    = "${var.name_prefix}-demo-s3-trigger-lambda-function"
  role             = aws_iam_role.lambda_exec.arn
  handler          = "process.lambda_handler"
  runtime          = "python3.11" # Use a modern, supported runtime
  timeout          = 30
  memory_size      = 128
  source_code_hash = data.archive_file.lambda_zip.output_base64sha256
}

# --- 5. Grant S3 Permission to Invoke Lambda ---
# This is crucial: S3 must be authorized to call the Lambda function
resource "aws_lambda_permission" "allow_s3_invocation" {
  statement_id  = "AllowExecutionFromS3"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.s3_processor.function_name
  principal     = "s3.amazonaws.com"
  source_arn    = aws_s3_bucket.demo.arn
}

# --- 6. Set up the S3 Bucket Notification (The Trigger) ---
# This tells the S3 bucket to send a notification to the Lambda function
# whenever a new object is created.
resource "aws_s3_bucket_notification" "lambda_trigger" {
  bucket = aws_s3_bucket.demo.id

  lambda_function {
    # Specify the file events that should trigger the lambda
    events       = ["s3:ObjectCreated:*"]
    # Link to the Lambda function ARN
    lambda_function_arn = aws_lambda_function.s3_processor.arn
  }

  # Ensures the Lambda permission is configured before setting the notification
  depends_on = [aws_lambda_permission.allow_s3_invocation]
}
